"""Hero-H1 stability across follow-up rebuilds (B173).

Operatörsfynd (2026-06-10, manuella klick-checkar /studio painter-palma): the
hero H1 got a NEW text on EVERY follow-up prompt — even prompts that never
mentioned the heading (a colour change, an opening-hours addition, a joke
test). Root cause: the rendered H1 comes from the planning blueprint
(``contentBlocks["home.hero"].headline``, derived from briefModel
``positioning.oneLiner``), which is regenerated by every follow-up rebuild.
The renderer's operator override ``company.heroHeadline`` survives rebuilds,
but it was only ever set by an explicit heading edit — a never-edited heading
had no anchor and drifted.

These tests lock the carry-forward fix in ``generate_followup``:

1. a follow-up WITHOUT heading intent pins the previously RENDERED H1 as
   ``company.heroHeadline`` in the merged Project Input, and the rendered H1
   stays identical to the previous version;
2. the pin alone renders the hero byte-identically (it can never by itself
   become a visible change — appliedVisibleEffect honesty falls out
   naturally);
3. an explicit "byt rubriken till X" follow-up still wins over the pin;
4. init generation never pins (the first build keeps its creative freedom);
5. no completed run -> no pin (nothing was rendered, nothing to carry);
6. deterministic no-key parity: every test here runs with OPENAI_API_KEY
   removed, i.e. the mock-no-key path behaves exactly the same.
"""

from __future__ import annotations

import copy
import json
import os
import time
from pathlib import Path
from typing import Any

import pytest

from packages.generation.build.blueprint_render import RenderBlueprint
from packages.generation.build.renderers import render_section_hero
from packages.generation.followup.theme_directives import ThemeDirective
from packages.generation.orchestration.apply import apply_patch_plan
from packages.generation.orchestration.patch import PatchPlan
from scripts.prompt_to_project_input import generate, generate_followup

# Core-lane (docs/testing.md): kärnflödet prompt -> bygge -> följdprompt.
pytestmark = pytest.mark.core

INIT_PROMPT = "Skapa en hemsida för en målerifirma i Palma."
SITE_ID = "painter-palma"
PROJECT_ID = "hero-stability-project"
PREVIOUS_HEADLINE = "Måleri i Palma med precision och omsorg"
REGENERATED_HEADLINE = "En helt ny regenererad blueprintrubrik"
# A real follow-up that carries no heading intent (tone-shift; same prompt
# family the versioning regression tests use).
NEUTRAL_FOLLOWUP = "Gör tonen mer premium och lägg mer fokus på snabb offert."


def _write_previous_run(
    runs_dir: Path,
    *,
    site_id: str = SITE_ID,
    headline: str | None = PREVIOUS_HEADLINE,
    run_id: str = "run-0001",
    version: int = 1,
) -> Path:
    """Fabricate the minimal run artefakts the carry-forward reads.

    ``build-result.json`` anchors the run to the site (same contract as
    ``build_site.py:_latest_run_id_for_site``); ``generation-package.json``
    carries the blueprint hero block the renderer consumed; ``input.json``
    maps the run to a Project Input version (read by the --base-run-id path).
    """
    run_dir = runs_dir / run_id
    run_dir.mkdir(parents=True, exist_ok=True)
    (run_dir / "build-result.json").write_text(
        json.dumps({"siteId": site_id}, ensure_ascii=False), encoding="utf-8"
    )
    content_blocks: dict[str, Any] = {}
    if headline is not None:
        content_blocks["home.hero"] = {
            "headline": headline,
            "subheadline": "En grundad underrubrik.",
        }
    (run_dir / "generation-package.json").write_text(
        json.dumps({"contentBlocks": content_blocks}, ensure_ascii=False),
        encoding="utf-8",
    )
    (run_dir / "input.json").write_text(
        json.dumps({"version": version}, ensure_ascii=False), encoding="utf-8"
    )
    return run_dir


def _init_then_followup(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
    *,
    followup_prompt: str,
    run_headline: str | None = PREVIOUS_HEADLINE,
    write_run: bool = True,
) -> tuple[dict[str, Any], dict[str, Any]]:
    """Run the real init + follow-up helper pair against tmp storage only."""
    monkeypatch.delenv("OPENAI_API_KEY", raising=False)
    output_dir = tmp_path / "prompt-inputs"
    runs_dir = tmp_path / "runs"
    initial_pi, _, _, _ = generate(
        INIT_PROMPT,
        output_dir=output_dir,
        site_id=SITE_ID,
        project_id=PROJECT_ID,
    )
    if write_run:
        _write_previous_run(runs_dir, headline=run_headline)
    followup_pi, _, _, _ = generate_followup(
        followup_prompt,
        site_id=SITE_ID,
        output_dir=output_dir,
        runs_dir=runs_dir,
    )
    return initial_pi, followup_pi


def _render_hero(dossier: dict[str, Any], blueprint: RenderBlueprint | None) -> str:
    return render_section_hero(
        dossier,
        dossier_routes=[],
        listing_route=None,
        contact_path="/kontakt",
        variant_id=dossier["variantId"],
        blueprint=blueprint,
    )


# ---------------------------------------------------------------------------
# 1. Follow-up WITHOUT heading intent -> previous rendered H1 is pinned
# ---------------------------------------------------------------------------


@pytest.mark.tooling
def test_followup_without_heading_intent_pins_previous_hero_headline(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    initial_pi, followup_pi = _init_then_followup(
        monkeypatch, tmp_path, followup_prompt=NEUTRAL_FOLLOWUP
    )
    assert "heroHeadline" not in initial_pi["company"], (
        "init must stay creative — the pin only exists on follow-ups"
    )
    assert followup_pi["company"]["heroHeadline"] == PREVIOUS_HEADLINE


@pytest.mark.tooling
def test_pinned_headline_renders_identical_h1_despite_regenerated_blueprint(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """The rebuild's regenerated blueprint proposes a brand-new headline, but
    the pinned override keeps the H1 the operator already saw."""
    _, followup_pi = _init_then_followup(
        monkeypatch, tmp_path, followup_prompt=NEUTRAL_FOLLOWUP
    )
    regenerated = RenderBlueprint(
        content_blocks={
            "home.hero": {
                "headline": REGENERATED_HEADLINE,
                "subheadline": "En grundad underrubrik.",
            }
        }
    )
    hero = _render_hero(copy.deepcopy(followup_pi), regenerated)
    assert PREVIOUS_HEADLINE in hero, "the previously rendered H1 must persist"
    assert REGENERATED_HEADLINE not in hero, (
        "the regenerated blueprint headline must lose to the carried-forward pin"
    )


# ---------------------------------------------------------------------------
# 2. Honesty: the pin alone is never a visible change
# ---------------------------------------------------------------------------


@pytest.mark.tooling
def test_pin_alone_renders_hero_byte_identically(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """Previous version rendered blueprint headline X; the pinned version
    renders override X over a regenerated blueprint Y. Byte-identical hero
    JSX => the pin can never by itself flip appliedVisibleEffect (which is a
    file-diff signal in build_site.py)."""
    initial_pi, followup_pi = _init_then_followup(
        monkeypatch, tmp_path, followup_prompt=NEUTRAL_FOLLOWUP
    )
    previous_blueprint = RenderBlueprint(
        content_blocks={
            "home.hero": {
                "headline": PREVIOUS_HEADLINE,
                "subheadline": "En grundad underrubrik.",
            }
        }
    )
    regenerated_blueprint = RenderBlueprint(
        content_blocks={
            "home.hero": {
                "headline": REGENERATED_HEADLINE,
                "subheadline": "En grundad underrubrik.",
            }
        }
    )
    hero_before = _render_hero(copy.deepcopy(initial_pi), previous_blueprint)
    # Isolate the pin: same dossier as v1 plus ONLY the carried-forward
    # heroHeadline, rendered against the drifted blueprint.
    pinned_dossier = copy.deepcopy(initial_pi)
    pinned_dossier["company"]["heroHeadline"] = followup_pi["company"][
        "heroHeadline"
    ]
    hero_after = _render_hero(pinned_dossier, regenerated_blueprint)
    assert hero_before == hero_after, (
        "the pin must reproduce the previous hero byte-for-byte"
    )


# ---------------------------------------------------------------------------
# 3. Explicit heading edits still win over the pin
# ---------------------------------------------------------------------------


@pytest.mark.tooling
def test_explicit_heading_change_wins_over_pin(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    _, followup_pi = _init_then_followup(
        monkeypatch,
        tmp_path,
        followup_prompt='Byt rubriken till "Palma målar bäst"',
    )
    assert followup_pi["company"]["heroHeadline"] == "Palma målar bäst"
    assert followup_pi["company"]["tagline"] == "Palma målar bäst"


@pytest.mark.tooling
def test_literal_replace_of_pinned_visible_headline_wins(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """Quoting the text the operator actually SEES as the H1 now works: the
    pin makes the rendered headline a stored copy field, so the B155 literal
    find-and-replace can match it instead of silently no-op:ing."""
    _, followup_pi = _init_then_followup(
        monkeypatch,
        tmp_path,
        followup_prompt=(
            f'ändra denna text "{PREVIOUS_HEADLINE}" till '
            '"Nymålad horisont på Mallorca"'
        ),
    )
    assert (
        followup_pi["company"]["heroHeadline"] == "Nymålad horisont på Mallorca"
    )


@pytest.mark.tooling
def test_existing_explicit_hero_headline_is_not_overwritten_by_pin(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """An operator-set heroHeadline from an earlier follow-up must survive a
    later neutral follow-up untouched, even when a newer run carries a
    different blueprint headline."""
    monkeypatch.delenv("OPENAI_API_KEY", raising=False)
    output_dir = tmp_path / "prompt-inputs"
    runs_dir = tmp_path / "runs"
    generate(
        INIT_PROMPT,
        output_dir=output_dir,
        site_id=SITE_ID,
        project_id=PROJECT_ID,
    )
    _write_previous_run(runs_dir, run_id="run-0001")
    explicit_pi, _, _, _ = generate_followup(
        'Byt rubriken till "Palma målar bäst"',
        site_id=SITE_ID,
        output_dir=output_dir,
        runs_dir=runs_dir,
    )
    assert explicit_pi["company"]["heroHeadline"] == "Palma målar bäst"
    newer_run = _write_previous_run(
        runs_dir, run_id="run-0002", headline="Regenererad rubrik v2", version=2
    )
    future = time.time() + 60
    os.utime(newer_run, (future, future))
    neutral_pi, _, _, _ = generate_followup(
        NEUTRAL_FOLLOWUP,
        site_id=SITE_ID,
        output_dir=output_dir,
        runs_dir=runs_dir,
    )
    assert neutral_pi["company"]["heroHeadline"] == "Palma målar bäst"


# ---------------------------------------------------------------------------
# 4. Init + no-run edges: the pin never fires without a rendered previous H1
# ---------------------------------------------------------------------------


@pytest.mark.tooling
def test_init_generation_never_pins(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    monkeypatch.delenv("OPENAI_API_KEY", raising=False)
    initial_pi, _, _, _ = generate(
        INIT_PROMPT,
        output_dir=tmp_path / "prompt-inputs",
        site_id=SITE_ID,
        project_id=PROJECT_ID,
    )
    assert "heroHeadline" not in initial_pi["company"]


@pytest.mark.tooling
def test_followup_without_previous_run_does_not_pin(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """No completed run for the site -> nothing was ever rendered -> no pin
    (the next build keeps the same freedom an init build has)."""
    _, followup_pi = _init_then_followup(
        monkeypatch, tmp_path, followup_prompt=NEUTRAL_FOLLOWUP, write_run=False
    )
    assert "heroHeadline" not in followup_pi["company"]


@pytest.mark.tooling
def test_pin_falls_back_to_company_name_when_blueprint_lacks_hero_block(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """A run whose generation package carries no home.hero block rendered
    company.name as the H1 (the renderer's template fallback) — that is the
    value that must carry forward."""
    initial_pi, followup_pi = _init_then_followup(
        monkeypatch, tmp_path, followup_prompt=NEUTRAL_FOLLOWUP, run_headline=None
    )
    assert (
        followup_pi["company"]["heroHeadline"]
        == initial_pi["company"]["name"]
    )


# ---------------------------------------------------------------------------
# 5. KÖR-7 apply seam (the /studio OpenClaw apply-bridge path)
# ---------------------------------------------------------------------------
# Scout-fynd på PR #264: /studio follow-ups go through runOpenClawFollowupApply
# -> run_followup_chain -> apply_patch_plan, which creates the next PI version
# WITHOUT generate_followup (route.ts early-returns on bridge.applied=true, so
# legacy Phase 1 never runs). The pin must therefore live in apply too.


@pytest.mark.tooling
def test_apply_patch_plan_theme_directive_pins_previous_hero_headline(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """A visual_style restyle through apply (no capability patch, theme only)
    pins the previously rendered H1 when company.heroHeadline is missing."""
    monkeypatch.delenv("OPENAI_API_KEY", raising=False)
    output_dir = tmp_path / "prompt-inputs"
    runs_dir = tmp_path / "runs"
    initial_pi, _, _, _ = generate(
        INIT_PROMPT,
        output_dir=output_dir,
        site_id=SITE_ID,
        project_id=PROJECT_ID,
    )
    assert "heroHeadline" not in initial_pi["company"]
    _write_previous_run(runs_dir)

    result = apply_patch_plan(
        PatchPlan(),
        site_id=SITE_ID,
        output_dir=output_dir,
        runs_dir=runs_dir,
        theme_directive=ThemeDirective(
            primaryColorHex="#db2777", toneVibe="editorial", colorWord="rosa"
        ),
    )
    assert result.applied is True
    v2_pi = json.loads(
        (output_dir / f"{SITE_ID}.v2.project-input.json").read_text(
            encoding="utf-8"
        )
    )
    assert v2_pi["company"]["heroHeadline"] == PREVIOUS_HEADLINE
    # The restyle itself still landed (the pin never blocks the apply edit).
    assert v2_pi["brand"]["primaryColorHex"] == "#db2777"


@pytest.mark.tooling
def test_apply_patch_plan_does_not_overwrite_existing_explicit_hero_headline(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """An operator-set heroHeadline survives an apply-driven follow-up even
    when the latest run carries a different blueprint headline."""
    monkeypatch.delenv("OPENAI_API_KEY", raising=False)
    output_dir = tmp_path / "prompt-inputs"
    runs_dir = tmp_path / "runs"
    generate(
        INIT_PROMPT,
        output_dir=output_dir,
        site_id=SITE_ID,
        project_id=PROJECT_ID,
    )
    # The operator set an explicit heading in the current version.
    current_path = output_dir / f"{SITE_ID}.project-input.json"
    current = json.loads(current_path.read_text(encoding="utf-8"))
    current["company"]["heroHeadline"] = "Operatörens egna rubrik"
    current_path.write_text(
        json.dumps(current, ensure_ascii=False, indent=2), encoding="utf-8"
    )
    _write_previous_run(runs_dir, headline="En annan blueprintrubrik")

    result = apply_patch_plan(
        PatchPlan(),
        site_id=SITE_ID,
        output_dir=output_dir,
        runs_dir=runs_dir,
        theme_directive=ThemeDirective(
            primaryColorHex="#db2777", toneVibe="editorial", colorWord="rosa"
        ),
    )
    assert result.applied is True
    v2_pi = json.loads(
        (output_dir / f"{SITE_ID}.v2.project-input.json").read_text(
            encoding="utf-8"
        )
    )
    assert v2_pi["company"]["heroHeadline"] == "Operatörens egna rubrik"


@pytest.mark.tooling
def test_followup_chain_restyle_pins_previous_hero_headline_end_to_end(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """Mock-no-key integration over the REAL chain (router -> patch -> apply):
    a neutral restyle on the painter-palma example yields a v2 Project Input
    whose pinned heroHeadline equals the H1 the v1 build actually rendered,
    and the rendered H1 stays unchanged even against a freshly regenerated
    blueprint."""
    monkeypatch.delenv("OPENAI_API_KEY", raising=False)
    from scripts.build_site import build, run_followup_chain

    repo_root = Path(__file__).resolve().parents[1]
    example = repo_root / "examples" / "painter-palma.project-input.json"
    site_id = "painter-palma"
    prompt_inputs = tmp_path / "prompt-inputs"
    prompt_inputs.mkdir()
    runs_dir = tmp_path / "runs"
    generated_dir = tmp_path / "gen"
    _target, v1_run_dir = build(
        example,
        do_build=False,
        runs_dir=runs_dir,
        generated_dir=generated_dir,
        prompt_inputs_dir=prompt_inputs,
    )
    package = json.loads(
        (v1_run_dir / "generation-package.json").read_text(encoding="utf-8")
    )
    v1_pi = json.loads(
        (prompt_inputs / f"{site_id}.v1.project-input.json").read_text(
            encoding="utf-8"
        )
    )
    hero_block = (package.get("contentBlocks") or {}).get("home.hero") or {}
    rendered_h1 = (hero_block.get("headline") or "").strip() or v1_pi[
        "company"
    ]["name"]
    assert "heroHeadline" not in v1_pi["company"]

    result = run_followup_chain(
        site_id,
        "ändra färgen till rosa",
        do_build=False,
        runs_dir=runs_dir,
        generated_dir=generated_dir,
        output_dir=prompt_inputs,
    )
    assert result["applied"] is True, result
    assert result["version"] == 2

    v2_pi = json.loads(
        (prompt_inputs / f"{site_id}.v2.project-input.json").read_text(
            encoding="utf-8"
        )
    )
    assert v2_pi["company"]["heroHeadline"] == rendered_h1, (
        "the apply-driven follow-up must carry the H1 the v1 build rendered"
    )
    # The H1 stays put even when the NEXT rebuild's brief regenerates a brand
    # new blueprint headline (the drift painter-palma showed in production).
    regenerated = RenderBlueprint(
        content_blocks={"home.hero": {"headline": REGENERATED_HEADLINE}}
    )
    hero = _render_hero(copy.deepcopy(v2_pi), regenerated)
    assert rendered_h1 in hero
    assert REGENERATED_HEADLINE not in hero


# ---------------------------------------------------------------------------
# 6. --base-run-id: the pin follows the run the operator iterates from
# ---------------------------------------------------------------------------


@pytest.mark.tooling
def test_base_run_id_pins_that_runs_headline(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    monkeypatch.delenv("OPENAI_API_KEY", raising=False)
    output_dir = tmp_path / "prompt-inputs"
    runs_dir = tmp_path / "runs"
    generate(
        INIT_PROMPT,
        output_dir=output_dir,
        site_id=SITE_ID,
        project_id=PROJECT_ID,
    )
    old_run = _write_previous_run(
        runs_dir, run_id="run-old", headline="Den gamla rubriken", version=1
    )
    newer_run = _write_previous_run(
        runs_dir, run_id="run-new", headline="Den nyaste rubriken", version=1
    )
    past = time.time() - 120
    os.utime(old_run, (past, past))
    future = time.time() + 60
    os.utime(newer_run, (future, future))
    followup_pi, _, _, _ = generate_followup(
        NEUTRAL_FOLLOWUP,
        site_id=SITE_ID,
        output_dir=output_dir,
        runs_dir=runs_dir,
        base_run_id="run-old",
    )
    assert followup_pi["company"]["heroHeadline"] == "Den gamla rubriken", (
        "iterating from a historical run must carry THAT run's rendered H1"
    )
