"""Hero-H1 stability across follow-up rebuilds (B173).

Operatörsfynd (2026-06-10, manuella klick-checkar /studio painter-palma): the
hero H1 got a NEW text on EVERY follow-up prompt — even prompts that never
mentioned the heading (a colour change, an opening-hours addition, a joke
test). Root cause: the rendered H1 comes from the planning blueprint
(``contentBlocks["home.hero"].headline``, derived from briefModel
``positioning.oneLiner``), which is regenerated by every follow-up rebuild.
The renderer's operator override ``company.heroHeadline`` survives rebuilds,
but it was only ever set by an explicit heading edit — a never-edited heading
had no anchor and drifted.

These tests lock the carry-forward fix in ``generate_followup``:

1. a follow-up WITHOUT heading intent pins the previously RENDERED H1 as
   ``company.heroHeadline`` in the merged Project Input, and the rendered H1
   stays identical to the previous version;
2. the pin alone renders the hero byte-identically (it can never by itself
   become a visible change — appliedVisibleEffect honesty falls out
   naturally);
3. an explicit "byt rubriken till X" follow-up still wins over the pin;
4. init generation never pins (the first build keeps its creative freedom);
5. no completed run -> no pin (nothing was rendered, nothing to carry);
6. deterministic no-key parity: every test here runs with OPENAI_API_KEY
   removed, i.e. the mock-no-key path behaves exactly the same.
"""

from __future__ import annotations

import copy
import json
import os
import time
from pathlib import Path
from typing import Any

import pytest

from packages.generation.build.blueprint_render import RenderBlueprint
from packages.generation.build.renderers import render_section_hero
from scripts.prompt_to_project_input import generate, generate_followup

INIT_PROMPT = "Skapa en hemsida för en målerifirma i Palma."
SITE_ID = "painter-palma"
PROJECT_ID = "hero-stability-project"
PREVIOUS_HEADLINE = "Måleri i Palma med precision och omsorg"
REGENERATED_HEADLINE = "En helt ny regenererad blueprintrubrik"
# A real follow-up that carries no heading intent (tone-shift; same prompt
# family the versioning regression tests use).
NEUTRAL_FOLLOWUP = "Gör tonen mer premium och lägg mer fokus på snabb offert."


def _write_previous_run(
    runs_dir: Path,
    *,
    site_id: str = SITE_ID,
    headline: str | None = PREVIOUS_HEADLINE,
    run_id: str = "run-0001",
    version: int = 1,
) -> Path:
    """Fabricate the minimal run artefakts the carry-forward reads.

    ``build-result.json`` anchors the run to the site (same contract as
    ``build_site.py:_latest_run_id_for_site``); ``generation-package.json``
    carries the blueprint hero block the renderer consumed; ``input.json``
    maps the run to a Project Input version (read by the --base-run-id path).
    """
    run_dir = runs_dir / run_id
    run_dir.mkdir(parents=True, exist_ok=True)
    (run_dir / "build-result.json").write_text(
        json.dumps({"siteId": site_id}, ensure_ascii=False), encoding="utf-8"
    )
    content_blocks: dict[str, Any] = {}
    if headline is not None:
        content_blocks["home.hero"] = {
            "headline": headline,
            "subheadline": "En grundad underrubrik.",
        }
    (run_dir / "generation-package.json").write_text(
        json.dumps({"contentBlocks": content_blocks}, ensure_ascii=False),
        encoding="utf-8",
    )
    (run_dir / "input.json").write_text(
        json.dumps({"version": version}, ensure_ascii=False), encoding="utf-8"
    )
    return run_dir


def _init_then_followup(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
    *,
    followup_prompt: str,
    run_headline: str | None = PREVIOUS_HEADLINE,
    write_run: bool = True,
) -> tuple[dict[str, Any], dict[str, Any]]:
    """Run the real init + follow-up helper pair against tmp storage only."""
    monkeypatch.delenv("OPENAI_API_KEY", raising=False)
    output_dir = tmp_path / "prompt-inputs"
    runs_dir = tmp_path / "runs"
    initial_pi, _, _, _ = generate(
        INIT_PROMPT,
        output_dir=output_dir,
        site_id=SITE_ID,
        project_id=PROJECT_ID,
    )
    if write_run:
        _write_previous_run(runs_dir, headline=run_headline)
    followup_pi, _, _, _ = generate_followup(
        followup_prompt,
        site_id=SITE_ID,
        output_dir=output_dir,
        runs_dir=runs_dir,
    )
    return initial_pi, followup_pi


def _render_hero(dossier: dict[str, Any], blueprint: RenderBlueprint | None) -> str:
    return render_section_hero(
        dossier,
        dossier_routes=[],
        listing_route=None,
        contact_path="/kontakt",
        variant_id=dossier["variantId"],
        blueprint=blueprint,
    )


# ---------------------------------------------------------------------------
# 1. Follow-up WITHOUT heading intent -> previous rendered H1 is pinned
# ---------------------------------------------------------------------------


@pytest.mark.tooling
def test_followup_without_heading_intent_pins_previous_hero_headline(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    initial_pi, followup_pi = _init_then_followup(
        monkeypatch, tmp_path, followup_prompt=NEUTRAL_FOLLOWUP
    )
    assert "heroHeadline" not in initial_pi["company"], (
        "init must stay creative — the pin only exists on follow-ups"
    )
    assert followup_pi["company"]["heroHeadline"] == PREVIOUS_HEADLINE


@pytest.mark.tooling
def test_pinned_headline_renders_identical_h1_despite_regenerated_blueprint(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """The rebuild's regenerated blueprint proposes a brand-new headline, but
    the pinned override keeps the H1 the operator already saw."""
    _, followup_pi = _init_then_followup(
        monkeypatch, tmp_path, followup_prompt=NEUTRAL_FOLLOWUP
    )
    regenerated = RenderBlueprint(
        content_blocks={
            "home.hero": {
                "headline": REGENERATED_HEADLINE,
                "subheadline": "En grundad underrubrik.",
            }
        }
    )
    hero = _render_hero(copy.deepcopy(followup_pi), regenerated)
    assert PREVIOUS_HEADLINE in hero, "the previously rendered H1 must persist"
    assert REGENERATED_HEADLINE not in hero, (
        "the regenerated blueprint headline must lose to the carried-forward pin"
    )


# ---------------------------------------------------------------------------
# 2. Honesty: the pin alone is never a visible change
# ---------------------------------------------------------------------------


@pytest.mark.tooling
def test_pin_alone_renders_hero_byte_identically(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """Previous version rendered blueprint headline X; the pinned version
    renders override X over a regenerated blueprint Y. Byte-identical hero
    JSX => the pin can never by itself flip appliedVisibleEffect (which is a
    file-diff signal in build_site.py)."""
    initial_pi, followup_pi = _init_then_followup(
        monkeypatch, tmp_path, followup_prompt=NEUTRAL_FOLLOWUP
    )
    previous_blueprint = RenderBlueprint(
        content_blocks={
            "home.hero": {
                "headline": PREVIOUS_HEADLINE,
                "subheadline": "En grundad underrubrik.",
            }
        }
    )
    regenerated_blueprint = RenderBlueprint(
        content_blocks={
            "home.hero": {
                "headline": REGENERATED_HEADLINE,
                "subheadline": "En grundad underrubrik.",
            }
        }
    )
    hero_before = _render_hero(copy.deepcopy(initial_pi), previous_blueprint)
    # Isolate the pin: same dossier as v1 plus ONLY the carried-forward
    # heroHeadline, rendered against the drifted blueprint.
    pinned_dossier = copy.deepcopy(initial_pi)
    pinned_dossier["company"]["heroHeadline"] = followup_pi["company"][
        "heroHeadline"
    ]
    hero_after = _render_hero(pinned_dossier, regenerated_blueprint)
    assert hero_before == hero_after, (
        "the pin must reproduce the previous hero byte-for-byte"
    )


# ---------------------------------------------------------------------------
# 3. Explicit heading edits still win over the pin
# ---------------------------------------------------------------------------


@pytest.mark.tooling
def test_explicit_heading_change_wins_over_pin(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    _, followup_pi = _init_then_followup(
        monkeypatch,
        tmp_path,
        followup_prompt='Byt rubriken till "Palma målar bäst"',
    )
    assert followup_pi["company"]["heroHeadline"] == "Palma målar bäst"
    assert followup_pi["company"]["tagline"] == "Palma målar bäst"


@pytest.mark.tooling
def test_literal_replace_of_pinned_visible_headline_wins(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """Quoting the text the operator actually SEES as the H1 now works: the
    pin makes the rendered headline a stored copy field, so the B155 literal
    find-and-replace can match it instead of silently no-op:ing."""
    _, followup_pi = _init_then_followup(
        monkeypatch,
        tmp_path,
        followup_prompt=(
            f'ändra denna text "{PREVIOUS_HEADLINE}" till '
            '"Nymålad horisont på Mallorca"'
        ),
    )
    assert (
        followup_pi["company"]["heroHeadline"] == "Nymålad horisont på Mallorca"
    )


@pytest.mark.tooling
def test_existing_explicit_hero_headline_is_not_overwritten_by_pin(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """An operator-set heroHeadline from an earlier follow-up must survive a
    later neutral follow-up untouched, even when a newer run carries a
    different blueprint headline."""
    monkeypatch.delenv("OPENAI_API_KEY", raising=False)
    output_dir = tmp_path / "prompt-inputs"
    runs_dir = tmp_path / "runs"
    generate(
        INIT_PROMPT,
        output_dir=output_dir,
        site_id=SITE_ID,
        project_id=PROJECT_ID,
    )
    _write_previous_run(runs_dir, run_id="run-0001")
    explicit_pi, _, _, _ = generate_followup(
        'Byt rubriken till "Palma målar bäst"',
        site_id=SITE_ID,
        output_dir=output_dir,
        runs_dir=runs_dir,
    )
    assert explicit_pi["company"]["heroHeadline"] == "Palma målar bäst"
    newer_run = _write_previous_run(
        runs_dir, run_id="run-0002", headline="Regenererad rubrik v2", version=2
    )
    future = time.time() + 60
    os.utime(newer_run, (future, future))
    neutral_pi, _, _, _ = generate_followup(
        NEUTRAL_FOLLOWUP,
        site_id=SITE_ID,
        output_dir=output_dir,
        runs_dir=runs_dir,
    )
    assert neutral_pi["company"]["heroHeadline"] == "Palma målar bäst"


# ---------------------------------------------------------------------------
# 4. Init + no-run edges: the pin never fires without a rendered previous H1
# ---------------------------------------------------------------------------


@pytest.mark.tooling
def test_init_generation_never_pins(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    monkeypatch.delenv("OPENAI_API_KEY", raising=False)
    initial_pi, _, _, _ = generate(
        INIT_PROMPT,
        output_dir=tmp_path / "prompt-inputs",
        site_id=SITE_ID,
        project_id=PROJECT_ID,
    )
    assert "heroHeadline" not in initial_pi["company"]


@pytest.mark.tooling
def test_followup_without_previous_run_does_not_pin(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """No completed run for the site -> nothing was ever rendered -> no pin
    (the next build keeps the same freedom an init build has)."""
    _, followup_pi = _init_then_followup(
        monkeypatch, tmp_path, followup_prompt=NEUTRAL_FOLLOWUP, write_run=False
    )
    assert "heroHeadline" not in followup_pi["company"]


@pytest.mark.tooling
def test_pin_falls_back_to_company_name_when_blueprint_lacks_hero_block(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """A run whose generation package carries no home.hero block rendered
    company.name as the H1 (the renderer's template fallback) — that is the
    value that must carry forward."""
    initial_pi, followup_pi = _init_then_followup(
        monkeypatch, tmp_path, followup_prompt=NEUTRAL_FOLLOWUP, run_headline=None
    )
    assert (
        followup_pi["company"]["heroHeadline"]
        == initial_pi["company"]["name"]
    )


# ---------------------------------------------------------------------------
# 5. --base-run-id: the pin follows the run the operator iterates from
# ---------------------------------------------------------------------------


@pytest.mark.tooling
def test_base_run_id_pins_that_runs_headline(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    monkeypatch.delenv("OPENAI_API_KEY", raising=False)
    output_dir = tmp_path / "prompt-inputs"
    runs_dir = tmp_path / "runs"
    generate(
        INIT_PROMPT,
        output_dir=output_dir,
        site_id=SITE_ID,
        project_id=PROJECT_ID,
    )
    old_run = _write_previous_run(
        runs_dir, run_id="run-old", headline="Den gamla rubriken", version=1
    )
    newer_run = _write_previous_run(
        runs_dir, run_id="run-new", headline="Den nyaste rubriken", version=1
    )
    past = time.time() - 120
    os.utime(old_run, (past, past))
    future = time.time() + 60
    os.utime(newer_run, (future, future))
    followup_pi, _, _, _ = generate_followup(
        NEUTRAL_FOLLOWUP,
        site_id=SITE_ID,
        output_dir=output_dir,
        runs_dir=runs_dir,
        base_run_id="run-old",
    )
    assert followup_pi["company"]["heroHeadline"] == "Den gamla rubriken", (
        "iterating from a historical run must carry THAT run's rendered H1"
    )
