"""Materialise a whitelisted generative component into a built site (ADR 0061).

Generative Component V1: the deterministic emit half of the component_builder
generative path. Given the ``directives.generativeComponents`` specs the apply
chain recorded (resolved by
``packages.generation.followup.generative_component_directives``), this writes
ONE new Server Component ``.tsx`` per spec under ``components/generated/<id>.tsx``
(the repo's component dir convention - ``mount_dossier_components`` writes to
``components/``, and ``@/*`` resolves to the project root in every starter
tsconfig) from a DETERMINISTIC, recipe-keyed template, then splices an ``import``
+ a usage element into the target route's ``page.tsx`` before its closing
``</main>`` (the same "inject before the closing main" shape the section
renderers use). NO LLM-generated free code and NO new npm dependencies in V1.

Hard guards (fail closed): every write is asserted to land INSIDE the build dir;
``package.json`` / ``package-lock.json`` / ``.env*`` / anything under
``node_modules`` is refused with :class:`GenerativeEmitError`; an unknown recipe
or an id that is not a safe filename slug raises (a contract violation - the
schema enum + the resolver should make these unreachable). A routeId whose
``page.tsx`` does not exist is an HONEST skip (no orphan component file written),
never a crash. Idempotent: re-running the same directive never double-inserts the
import or the usage element.

Conventions: identifiers + comments in English (governance/rules/code-in-english.md).
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any

__all__ = [
    "GenerativeEmitError",
    "materialize_generative_components",
]

# Filename/route slug guard: lowercase, digits and single hyphens, never a dot or
# slash (so an id can never be ``..`` or escape ``components/generated/``). Mirrors
# the schema pattern for ``directives.generativeComponents[].id``.
_SAFE_SLUG = re.compile(r"^[a-z0-9][a-z0-9-]*$")

# A leading React directive ("use client" / "use server") MUST remain the FIRST
# statement in the file; an import prepended before it breaks the Next.js build.
# This matches such a directive (either quote style, optional semicolon) at the
# very top so a generated import is inserted AFTER it instead of before.
_LEADING_DIRECTIVE_RE = re.compile(
    r"^\s*(?:\"use (?:client|server)\"|'use (?:client|server)')\s*;?[ \t]*\r?\n"
)

# The opening <main ...> tag (with optional attributes). Used to honour a "top"
# placement: a generative component asked to land "högst upp" is spliced right
# AFTER this tag (first child of <main>), instead of the default before-</main>.
_OPENING_MAIN_RE = re.compile(r"<main\b[^>]*>")

# The V1 recipe allowlist. A spec whose recipe is not here is a contract violation
# (the schema enum + the resolver allowlist should make it unreachable); we fail
# closed rather than write an unknown template. Each value is a template renderer
# ``(component_name, count) -> tsx source``.


class GenerativeEmitError(Exception):
    """Raised on any path/policy violation while materialising a component."""


def _render_image_placeholder_grid(component_name: str, count: int) -> str:
    """Deterministic ``image-placeholder-grid`` template (no external deps).

    A responsive grid of ``count`` placeholder tiles - plain ``<div>`` elements
    with an aspect-ratio + a subtle background, using Tailwind classes the
    starters already ship. No ``next/image`` remote config, no new npm package.
    """
    return (
        "// Auto-generated by Sajtbyggaren Generative Component V1 (ADR 0061).\n"
        "// Recipe: image-placeholder-grid. Deterministic Server Component with no\n"
        "// external dependencies and no new npm packages (V1 write-path proof).\n"
        f"export function {component_name}() {{\n"
        f"  const tiles = Array.from({{ length: {count} }}, (_, index) => index);\n"
        "  return (\n"
        '    <section aria-label="Bildplatshållare" className="w-full px-6 py-16 md:px-10">\n'
        '      <div className="mx-auto grid max-w-6xl grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-4">\n'
        "        {tiles.map((tile) => (\n"
        "          <div\n"
        "            key={tile}\n"
        '            aria-hidden="true"\n'
        '            className="aspect-square rounded-xl bg-neutral-200/80 ring-1 ring-inset ring-neutral-300/70 dark:bg-neutral-800/70 dark:ring-neutral-700/70"\n'
        "          />\n"
        "        ))}\n"
        "      </div>\n"
        "    </section>\n"
        "  );\n"
        "}\n"
        "\n"
        f"export default {component_name};\n"
    )


_RECIPE_TEMPLATES: dict[str, Any] = {
    "image-placeholder-grid": _render_image_placeholder_grid,
}


def _assert_safe_write_path(build_root: Path, path: Path) -> Path:
    """Return the resolved ``path`` after asserting it is a safe write target.

    Fail closed: the path must resolve INSIDE ``build_root`` and must never be
    ``package.json`` / ``package-lock.json`` / ``.env*`` / anything under
    ``node_modules``. Any violation raises :class:`GenerativeEmitError` so a
    buggy/hand-edited directive can never write outside the build dir or touch a
    dependency/secret surface.
    """
    build_root = build_root.resolve()
    resolved = path.resolve()
    if resolved != build_root and build_root not in resolved.parents:
        raise GenerativeEmitError(
            f"refusing to write outside the build dir: {resolved} (build={build_root})"
        )
    rel_parts = resolved.relative_to(build_root).parts
    if "node_modules" in rel_parts:
        raise GenerativeEmitError(f"refusing to write under node_modules: {resolved}")
    name = resolved.name
    if name in ("package.json", "package-lock.json") or name.startswith(".env"):
        raise GenerativeEmitError(f"refusing to write a protected file: {resolved}")
    return resolved


def _write_text(path: Path, contents: str) -> None:
    """Write text with LF newlines (mirrors scripts.build_site.write)."""
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write(contents)


def _component_name(component_id: str) -> str:
    """Derive a deterministic PascalCase React component name from the id."""
    parts = [segment for segment in re.split(r"[^a-z0-9]+", component_id) if segment]
    pascal = "".join(segment[:1].upper() + segment[1:] for segment in parts)
    return f"Generated{pascal}" if pascal else "GeneratedComponent"


def _page_path_for_route(target: Path, route_id: str) -> Path | None:
    """Resolve the ``page.tsx`` a route's component splices into, or None.

    V1 supports the home route (``app/page.tsx``); any other safe-slug routeId
    maps to ``app/<routeId>/page.tsx`` when it exists. A missing page is an
    HONEST skip (return None) so no orphan component file is written, never a
    crash. A routeId that is not a safe path segment also returns None.
    """
    if route_id in ("home", "", "/"):
        candidate = target / "app" / "page.tsx"
    elif _SAFE_SLUG.match(route_id):
        candidate = target / "app" / route_id / "page.tsx"
    else:
        return None
    return candidate if candidate.exists() else None


def _prepend_import(text: str, import_line: str) -> str:
    """Insert ``import_line`` at the top, but AFTER a leading React directive.

    A ``"use client"`` / ``"use server"`` directive must stay the file's FIRST
    statement; prepending an import before it breaks the Next.js build (bug fix).
    When such a directive leads the file the import goes right after it; otherwise
    it goes at the very top (unchanged for the common server-component page).
    """
    match = _LEADING_DIRECTIVE_RE.match(text)
    if match:
        return text[: match.end()] + import_line + text[match.end() :]
    return import_line + text


def _insert_before_closing_main(text: str, usage_line: str) -> str | None:
    """Insert ``usage_line`` immediately before the LAST ``</main>``, or None.

    The default placement (and the same "before the closing main" shape the
    section renderers use). Returns None when the page has no ``</main>``.
    """
    marker = "</main>"
    idx = text.rfind(marker)
    if idx == -1:
        return None
    line_start = text.rfind("\n", 0, idx) + 1
    return text[:line_start] + usage_line + text[line_start:]


def _insert_after_opening_main(text: str, usage_line: str) -> str | None:
    """Insert ``usage_line`` right AFTER the first opening ``<main ...>`` tag.

    Honours a "top" placement ("högst upp"): the component becomes the first
    child of ``<main>``, before the hero/first section. ``usage_line`` carries
    its own trailing newline, so it is placed on its own line after the opening
    tag's line. Returns None when the page has no opening ``<main>`` tag (the
    caller then falls back to the default before-``</main>`` placement).
    """
    match = _OPENING_MAIN_RE.search(text)
    if match is None:
        return None
    end = match.end()
    rest = text[end:]
    if rest.startswith("\r\n"):
        newline, rest = "\r\n", rest[2:]
    elif rest.startswith("\n"):
        newline, rest = "\n", rest[1:]
    else:
        newline = ""
    return text[:end] + newline + usage_line + rest


def _splice_into_page(
    page_text: str, *, import_line: str, usage_line: str, position: str | None = None
) -> str | None:
    """Return ``page_text`` with the import + usage spliced in, or None to skip.

    ``position`` honours the router-derived placement (the same ``top``/``bottom``
    tokens section_add uses, RouterTarget.position): ``"top"`` splices the usage
    right after the opening ``<main>`` (first child); ``"bottom"`` and the default
    (``None`` / ``"before-contact"``) splice it before the LAST ``</main>`` - the
    unchanged behaviour. A ``"top"`` request on a page with no opening ``<main>``
    falls back to the default placement rather than skipping.

    ``import_line`` is inserted at the top - but AFTER any leading ``"use client"``
    directive (which must remain the first statement, or the Next.js build breaks).
    Idempotent: an already present import or usage is left untouched, so re-running
    never double-inserts. Returns None when the page has no ``</main>`` to splice
    into (honest skip).
    """
    text = page_text
    component_token = usage_line.strip()
    if component_token not in text:
        spliced: str | None = None
        if position == "top":
            spliced = _insert_after_opening_main(text, usage_line)
        if spliced is None:
            spliced = _insert_before_closing_main(text, usage_line)
        if spliced is None:
            return None
        text = spliced
    if import_line not in text:
        text = _prepend_import(text, import_line)
    return text


def materialize_generative_components(
    target: Path,
    directives: list[dict[str, Any]],
    *,
    trace: Any | None = None,
) -> list[str]:
    """Materialise each generative-component spec into the built site at ``target``.

    ``target`` is the build directory (``<generated>/<siteId>/builds/<id>/``).
    ``directives`` are the ``directives.generativeComponents`` specs (each
    ``{recipe, count, routeId, id}``) read from the Project Input dossier by
    ``scripts.build_site._generative_components_from_dossier``. For each spec this
    writes ``components/generated/<id>.tsx`` from the recipe template and splices
    an import + usage element into the target route's ``page.tsx``.

    Returns the list of ``components/generated/<id>.tsx`` paths (relative to
    ``target``) that were written. Idempotent (re-running never double-inserts);
    fail-closed on any path/policy violation (raises :class:`GenerativeEmitError`).
    An unknown recipe or unsafe id raises; a routeId whose page does not exist is
    an honest skip. ``trace`` (optional) receives one ``generative.materialized``
    event per written component.
    """
    target = Path(target)
    written: list[str] = []
    for spec in directives or []:
        if not isinstance(spec, dict):
            raise GenerativeEmitError(f"generative spec must be an object: {spec!r}")
        recipe = spec.get("recipe")
        component_id = spec.get("id")
        route_id = spec.get("routeId") or "home"
        count = spec.get("count")
        # Placement: the resolver records the router-derived position (top/bottom)
        # only when the prompt named one; absent = default before-</main>.
        position = spec.get("position")

        renderer = _RECIPE_TEMPLATES.get(recipe) if isinstance(recipe, str) else None
        if renderer is None:
            raise GenerativeEmitError(
                f"unknown generative recipe {recipe!r}; V1 allows only "
                f"{sorted(_RECIPE_TEMPLATES)} (never an invented component)."
            )
        if not isinstance(component_id, str) or not _SAFE_SLUG.match(component_id):
            raise GenerativeEmitError(
                f"unsafe generative component id {component_id!r}; must match "
                f"{_SAFE_SLUG.pattern} (no traversal, no slashes)."
            )
        clamped_count = max(1, min(12, int(count) if isinstance(count, int) else 6))

        page_path = _page_path_for_route(target, str(route_id))
        if page_path is None:
            # Honest skip: no page to splice into -> never an orphan component file.
            continue

        # Guard BOTH write targets before touching disk (fail closed).
        component_path = _assert_safe_write_path(
            target, target / "components" / "generated" / f"{component_id}.tsx"
        )
        page_path = _assert_safe_write_path(target, page_path)

        component_name = _component_name(component_id)
        spliced = _splice_into_page(
            page_path.read_text(encoding="utf-8"),
            import_line=(
                f'import {{ {component_name} }} from '
                f'"@/components/generated/{component_id}";\n'
            ),
            usage_line=f"      <{component_name} />\n",
            position=position if isinstance(position, str) else None,
        )
        if spliced is None:
            # The page has no </main> to splice into -> honest skip, no orphan.
            continue

        _write_text(component_path, renderer(component_name, clamped_count))
        _write_text(page_path, spliced)

        rel = f"components/generated/{component_id}.tsx"
        written.append(rel)
        if trace is not None:
            trace.event(
                "build",
                "generative.materialized",
                "done",
                f"Materialised generative component {recipe} -> {rel}",
                reason=f"routeId={route_id}, count={clamped_count}",
            )
    return written
