"""Hero-headline carry-forward across follow-up rebuilds (B173).

The rendered hero H1 comes from the planning blueprint
(``contentBlocks["home.hero"].headline``, derived from briefModel
``positioning.oneLiner``), which is REGENERATED by every follow-up rebuild —
so the big headline drifted on EVERY follow-up even when the prompt never
mentioned it (operatörsfynd 2026-06-10, manuella klick-checkar /studio
painter-palma). The renderer already prefers the operator override
``company.heroHeadline`` over the regenerated blueprint headline (contract
heroHeadline > blueprint > company.name, fb9692d) — but the field was only
set by an explicit heading edit, so a never-edited heading had no anchor.

Carry-forward: when the previous version carries NO explicit heroHeadline,
pin the headline its build ACTUALLY rendered (blueprint headline, else
company.name — the renderer's own fallback chain) onto the follow-up merge
base. The pin reproduces the previous H1 byte-for-byte, so it can never by
itself flip ``appliedVisibleEffect``; an explicit "byt rubriken till X"
still wins because ``_apply_copy_directives`` mirrors the new tagline over
the pin. Init generation never pins (nothing was rendered yet).

Shared seam (Scout-fynd på PR #264): BOTH follow-up version creators call
this module —

- ``scripts/prompt_to_project_input.py:generate_followup`` (the legacy
  Phase 1+2 prompt follow-up, CLI ``--followup-site-id``), and
- ``packages/generation/orchestration/apply/apply.py:apply_patch_plan``
  (the KÖR-7 chain behind ``run_followup_chain`` / the /studio OpenClaw
  apply-bridge, which creates the next version WITHOUT generate_followup).

Stdlib-only on purpose: importable from both sides with zero circular-
dependency risk.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

__all__ = [
    "HERO_HEADLINE_PIN_MAX_LENGTH",
    "latest_run_dir_for_site",
    "pin_previous_hero_headline",
    "run_blueprint_hero_headline",
]

# project-input.schema.json caps company.heroHeadline at 200 chars. A longer
# rendered headline is left unpinned (drift accepted for that pathological
# case) rather than truncated — a truncated pin would CHANGE the H1, which
# the pin must never do.
HERO_HEADLINE_PIN_MAX_LENGTH = 200


def latest_run_dir_for_site(runs_dir: Path, site_id: str) -> Path | None:
    """Newest run dir whose build-result.json belongs to ``site_id``.

    Mirrors ``scripts/build_site.py:_latest_run_id_for_site`` (mtime order,
    read-only). Returns ``None`` when the site has no completed run yet —
    then nothing was ever rendered, so there is no headline to carry forward.
    """
    try:
        candidates = sorted(
            (entry for entry in runs_dir.iterdir() if entry.is_dir()),
            key=lambda entry: entry.stat().st_mtime,
            reverse=True,
        )
    except OSError:
        return None
    for run_dir in candidates:
        try:
            payload = json.loads(
                (run_dir / "build-result.json").read_text(encoding="utf-8")
            )
        except (OSError, json.JSONDecodeError):
            continue
        if payload.get("siteId") == site_id:
            return run_dir
    return None


def run_blueprint_hero_headline(run_dir: Path) -> str | None:
    """The blueprint hero headline a run rendered, else ``None``.

    Reads ``generation-package.json`` ``contentBlocks["home.hero"].headline``
    — the exact field the renderer consumes (``RenderBlueprint.hero("home")``
    in ``packages/generation/build``) when no operator override exists.
    Defensive at every level: a missing or malformed artefakt yields ``None``.
    """
    try:
        package = json.loads(
            (run_dir / "generation-package.json").read_text(encoding="utf-8")
        )
    except (OSError, json.JSONDecodeError):
        return None
    blocks = package.get("contentBlocks") if isinstance(package, dict) else None
    hero = blocks.get("home.hero") if isinstance(blocks, dict) else None
    headline = hero.get("headline") if isinstance(hero, dict) else None
    if isinstance(headline, str) and headline.strip():
        return headline.strip()
    return None


def pin_previous_hero_headline(
    previous_project_input: dict[str, Any],
    *,
    run_dir: Path | None,
) -> None:
    """Pin the previously rendered hero H1 as ``company.heroHeadline``.

    Mutates the follow-up merge base in place. No-op when (a) the operator
    already set an explicit heroHeadline (it carries forward via the merge
    deepcopy by itself), (b) the site has no completed run (nothing was
    rendered — the first build keeps its creative freedom), or (c) no honest
    headline source exists. The pinned value is EXACTLY what the previous
    build rendered, so the pin alone never produces a visible diff.
    """
    if run_dir is None:
        return
    company = previous_project_input.get("company")
    if not isinstance(company, dict):
        return
    existing = company.get("heroHeadline")
    if isinstance(existing, str) and existing.strip():
        return
    headline = run_blueprint_hero_headline(run_dir)
    if headline is None:
        # No blueprint hero block -> that run's H1 fell back to company.name
        # (packages/generation/build/renderers.py:render_section_hero).
        name = company.get("name")
        headline = name.strip() if isinstance(name, str) and name.strip() else None
    if headline is None or len(headline) > HERO_HEADLINE_PIN_MAX_LENGTH:
        return
    company["heroHeadline"] = headline
